pull_request_rules:
  - name: automatic merge renovate PR
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - author=renovate[bot]
      - status-success=DCO
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
    actions:
      delete_head_branch: {}
      merge:
       strict: smart
  - name: merge iamsaurav PR
    conditions:
      - author=iamsauravsharma
      - status-success=DCO
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
    actions:
      delete_head_branch: {}
      merge:
       strict: smart