pull_request_rules:
  - name: automatic merge renovate bot PR
    conditions:
      - author=renovate[bot]
      - label=dependencies
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
    actions:
      delete_head_branch: {}
      merge:
       strict: smart
  - name: merge iamsauravsharma PR
    conditions:
      - author=iamsauravsharma
      - status-success=DCO
      - label!=WIP
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
      - status-success=WIP
    actions:
      delete_head_branch: {}
      merge:
       strict: smart
  - name: merge reviewed check pass commit
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - approved-reviews-by=iamsauravsharma
      - label!=WIP
      - status-success=DCO
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
      - status-success=WIP
    actions:
      merge:
       strict: smart