unstable_features=true
wrap_comments=true
edition="2018"
format_strings=true
merge_imports=true
merge_derives=true
normalize_comments=true
reorder_imports=true
reorder_modules=true
reorder_impl_items=true
report_todo="Always"
report_fixme="Always"
format_code_in_doc_comments=true
combine_control_expr=false
use_field_init_shorthand=true
use_try_shorthand=true
normalize_doc_attributes=true