unstable_features=true
wrap_comments=true
edition="2018"
format_strings=true
imports_layout="Vertical"
merge_imports=true
merge_derives=true
normalize_comments=true
reorder_imports=true
reorder_modules=true
reorder_impl_items=true
report_todo="Always"
report_fixme="Always"
format_doc_comments=true