language: rust

rust:
  - stable
  - beta
  - nightly
  # minimum version support
  - 1.31.0

git:
  depth: false
 
dist: xenial
  
os:
  - linux
  - osx
  - windows

install:
  - rustup component add rustfmt
  - rustup component add clippy

before_script:
  - rustfmt -V
  - cargo clippy -V

script:
  - cargo fmt --verbose --all -- --check
  - cargo clippy --verbose --all -- -D warnings
  - cargo build --verbose --all
  - cargo doc --no-deps --all
  - cargo test --verbose --all