language: rust

rust:
  - nightly

git:
  depth: false

cache: cargo

os:
  - linux
  - osx
  - windows

install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview

before_script:
  - rustfmt -V
  - cargo clippy -V

script:
  - cargo fmt --verbose --all -- --check
  - cargo clippy --verbose --all -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all