language: rust

rust:
  - stable
  - beta
  - nightly

git:
  depth: false
 
dist: xenial
  
os:
  - linux
  - osx
  - windows

install:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      rustup component add rustfmt;
    fi
  - rustup component add clippy

before_script:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      rustfmt -V;
    fi
  - cargo clippy -V

script:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo fmt --verbose --all -- --check;
    fi
  - cargo clippy --verbose --all -- -D warnings
  - cargo build --verbose --all
  - cargo doc --no-deps --all
  - cargo test --verbose --all