language: rust

rust:
  - stable
  - beta
  - nightly

git:
  depth: false
 
dist: xenial
  
os:
  - linux
  - osx
  - windows

install:
  - rustup component add rustfmt
  - rustup component add clippy

before_script:
  - rustfmt -V || RUSTFMT="no"
  - cargo clippy -V || CLIPPY="no"

script:
  - if [[ ! "RUSTFMT" == "no" ]]; then
      cargo fmt --verbose --all -- --check;
    fi
  - if [[ ! "CLIPPY" == "no" ]]; then
      cargo clippy --verbose --all -- -D warnings;
    fi
  - cargo build --verbose --all
  - cargo doc --no-deps --all
  - cargo test --verbose --all