language: rust

git:
  depth: false
 
dist: xenial

matrix:
  include:
  - os: linux
  - os: osx
  - os: windows
  - rust: beta
  - rust: nightly

install:
  - rustup component add rustfmt && RUSTFMT="yes" || RUSTFMT="no"
  - rustup component add clippy && CLIPPY="yes" || CLIPPY="no"

before_script:
  - if [[ "$RUSTFMT" == "yes" ]]; then
      rustfmt -V;
    fi
  - if [[ "$CLIPPY" == "yes" ]]; then
      cargo clippy -V;
    fi

script:
  - if [[ "$RUSTFMT" == "yes" ]]; then
      cargo fmt --all -- --check;
    fi
  - if [[ "$CLIPPY" == "yes" ]]; then
      cargo clippy --all -- -D warnings;
    fi
  - cargo build --all
  - cargo doc --no-deps --all --all-features
  - cargo test --all --all-features

deploy:
  provider: cargo
  token: $CARGO_TOKEN
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = stable