language: rust

rust:
  - nightly

git:
  depth: false

cache: cargo

os:
  - linux
  - osx
  - windows

install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
  - cargo install cargo-deadlinks --force

before_script:
  - rustfmt -V
  - cargo deadlinks -V
  - cargo clippy -V

script:
  - cargo fmt  --verbose --all -- --check
  - cargo doc --verbose --no-deps
  - cargo deadlinks --verbose --dir target/doc
  - cargo clippy --verbose --all -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all