language: rust

rust:
  - nightly

git:
  depth: false

cache: cargo

jobs:
  
  include:
  - name: fmt
    install: 
    - rustup component add rustfmt-preview
    - rustfmt -V
    script:
    - cargo fmt --all -- --check
  
  - name: deadlinks
    install:
    - cargo install cargo-deadlinks --force
    - cargo deadlinks -V
    script:
    - cargo doc --no-deps
    - cargo deadlinks --dir target/doc
  
  - name : clippy
    install:
    - rustup component add clippy-preview
    - cargo clippy -V
    script:
    - cargo clippy --all -- -D warnings

  - name: test
    script:
    - cargo test --all

  - name: build
    script:
    - cargo build --all