[package]
name = "cargo-trim"
version = "0.1.0"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
edition = "2018"
description="Binary application to cleanup $CARGO_HOME cache"
license="MIT"

[dependencies]
clap="2.32.0"
dirs="1.0.5"
serde="1.0.89"
serde_json="1.0.39"
serde_derive="1.0.89"
fs_extra="1.1.0"
colored="1.7.0"