[package]
name = "cargo-trim"
version = "0.1.0"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
edition = "2018"
description="Binary application to cleanup .cargo/registry cache"
license="MIT"

[dependencies]
clap="2.32.0"
dirs="1.0.4"
serde="1.0.85"
serde_json="1.0.37"
serde_derive="1.0.85"
fs_extra="1.1.0"