[package]
name = "cargo-trim"
version = "0.2.0"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
homepage = "https://github.com/iamsauravsharma/cargo-trim"
repository = "https://github.com/iamsauravsharma/cargo-trim"
description = "Binary application to cleanup $CARGO_HOME cache"
license = "MIT"
readme = "README.MD"
edition = "2018"
keywords = ["cargo","cache","remove","manage","clean"]
categories = ["command-line-utilities"]

[dependencies]
clap = "2.33.0"
dirs = "1.0.5"
serde = "1.0.91"
serde_json = "1.0.39"
serde_derive = "1.0.91"
fs_extra = "1.1.0"
colored = {version="1.8.0",optional=true}

[features]
default = ["colored-output"]
colored-output = ["colored"]
non-colored-output = []