[package]
name = "cargo-cleaner"
version = "0.1.0"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
edition = "2018"
description="Binary application to cleanup .cargo/registry cache"
license="MIT"

[dependencies]
clap="2.32.0"
dirs="1.0.4"